### ISSUE TITLE
Indicate that node 4 is not supported

### ISSUE THREAD

**Issue by mccollam** [resin-io/resin-preload#123]
This script relies on features that are not present in node 4 (e.g. `fs.constants`).  However, since this is the version you get when you `apt-get install` node in the current Ubuntu LTS, it's probably worth pointing out in documentation somewhere that this will fail.  (Bonus points for refusing to install or run on legacy node versions.)

The behavior seen when trying to run under node 4 is:

```
$ sudo resin-preload --app ${APP_ID} --api-token ${API_TOKEN} --img resin-image.img
Building Docker preloader image. [========================] 100%

[TypeError: Cannot read property 'R_OK' of undefined]
```

**Comment by zvin** [comment]
This was fixed by https://github.com/resin-io/resin-preload/pull/124
