### ISSUE TITLE
Some images have important data outside of partitions or partition tables.

### ISSUE THREAD

**Issue by zvin** [resin-io/resin-preload#127]
Like Variscite DART-6UL for example.

It's a flashed type device.

When preloading this type of image, the preload script needs to recreate a disk image in order to be able to move partitions after the root partition (which needs to be resized).
This process creates the new partition table using sfdisk and then copies the partitions from the old image to the new one.
This means that data outside of partitions is not copied.

As https://community.nxp.com/docs/DOC-95015 says,
> U-boot should reside at offset 1024B of your SD card.

We need to copy data between the partition table and the first partition to the new image.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_38s1)

**Comment by lurch** [comment]
ping @jhermsmeier and @jviotti - this is obviously something to be aware of in Etcher too, when we add the "dynamic blockmap" code and ignore any non-partitioned diskspace.
