### ISSUE TITLE
Add option to preload config.json

### ISSUE THREAD

**Issue by mccollam** [resin-io/resin-preload#132]
It would be nice to be able to use the resin-preload script to modify a resinOS image to use a provided config.json.  This would make using a single resinOS image for different applications or users much easier.

**Comment by lurch** [comment]
Forgive my ignorance, but does https://github.com/resin-io/resin-plugin-img (which is linked to from this repo's README) allow you to do that?

**Comment by shaunmulligan** [comment]
@mccollam I think this functionality is better implemented in the `resin configure`, we could perhaps have that hook on to the end of `resin preload` but it seems like we are making preload do to much already. cc @pimterry just because he is working on the configuration stuff currently

**Comment by pimterry** [comment]
Yep, the CLI already has a `resin config inject` command that does exactly this (I think, though I've never used it), and `resin device configure` that takes your device uuid (or app id, soon: https://github.com/resin-io/resin-cli/issues/691), builds the appropriate config.json internally and injects that.

@mccollam do those cover your use case? We could pretty easily make `resin preload` in the CLI optionally run one of those for you, but I'm with @shaunmulligan - keeping the individual commands simpler and decoupled sounds better to me.

**Comment by mccollam** [comment]
@pimterry sorry, missed this previously.  Yeah, I think that covers this use case for sure -- I didn't realize tat `resin config inject` was already there when I filed this.  So it's probably safe to close this :)
