### ISSUE TITLE
Support flasher type images

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io/resin-preload#37]
Support "flasher type" images which flash to internal storage devices (eMMC, etc.).
Note: Images of this type are used for Beaglebones, NUCs and UP boards.

- [x] Detect whether it's a "flasher type" image
- [x] Read `yocto.deployArtifact` key from `device-type.json`, replace `'-flasher'' to get filename
- [x] move the partitions 3, 4, 5 and 6 to make space for partition 3
- [x] resize the partition 2
- [x] mount the `${filename}.resinos-img` from `/opt` of the 2nd partition (rootfs)
- [x] resize it to fit the application container
- [x] preload application into that

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1i41)

**Comment by floion** [comment]
Hi, any progress on this?

**Comment by zvin** [comment]
for point 2: `jq -r '.yocto.deployArtifact' boot/device-type.json | sed s/flasher-//`

**Comment by zvin** [comment]
@floion I'm working on it, but I'll be on vacation until July 18th.
