### ISSUE TITLE
Error: /img/resin.img: unrecognised disk label

### ISSUE THREAD

**Issue by diegosucaria** [resin-io/resin-preload#44]
Hi, I tried to use the script but got this error, I'm using Docker for mac. latest resin os 2.x img.

![screen shot 2017-05-29 at 10 10 35 am](https://cloud.githubusercontent.com/assets/4278322/26551077/37635496-4457-11e7-80e7-be7ceeec73bf.png)

**Comment by jhermsmeier** [comment]
Hey @diegosucaria, can you post the exact command you used to run this (and also the full log), as well as the docker version?

**Comment by diegosucaria** [comment]
Sure, this is what I did:

```
git clone https://github.com/resin-io/resin-preload-image-script.git
cd resin-preload-image-script/
docker build -t resin/resin-preload .
./preload.sh --app 'app number here' --api-token 'token here' --img resin.img
```

I manually put the image I dowloaded from the dashboard into the folder and renamed it to resin.img to make things easier.

also, Im on mac and had to install `brew install coreutils`  since the script has a command called **realpath** and it is not installed by default.

Docker:  Version 17.03.1-ce-mac5 (16048)

**Comment by zvin** [comment]
@diegosucaria I see this in your screenshot:

```
Warning: Unable to open /img/resin.img read-write (Is a directory).  /img/resin.img has been opened read-only.
```

I guess you've given the wrong path to the `--img` parameter.
I can reproduce it with `--img /some/directory`.
