### ISSUE TITLE
Support argument for build hash to pre-load

### ISSUE THREAD

**Issue by BrianAdams** [resin-io/resin-preload#64]
With staged deployments, it appears that the resin-preload gets whatever build version has been set as the current default for the application.  

Our use case is that we create preloaded images of each build and we use those to test before we release the build to the fleet as an upgrade.  

If the resin-preload could add an optional parameter to allow specifying the particular build to load, it would make working with the staged deployments easier.

**Comment by zvin** [comment]
@BrianAdams you should now be able to use the --commit option to preload a specific version: https://www.npmjs.com/package/resin-preload

**Comment by BrianAdams** [comment]
Thanks, when do you kick off the build for the updated docker container push to docker hub?  https://hub.docker.com/r/resin/resin-preload/

**Comment by BrianAdams** [comment]
@zvin ment to mention in above question regarding docker container deployment.

**Comment by zvin** [comment]
@BrianAdams this docker image is no longer used by resin-preload. It is built before preloading from the included Dockerfile: https://github.com/resin-io/resin-preload/blob/master/bin/resin-preload#L143
