### ISSUE TITLE
Must use full file-path for --img

### ISSUE THREAD

**Issue by taeold** [resin-io/resin-preload#74]
resin-preload tool is really cool - thanks for creating and sharing it.

Small nit I noticed while using the tool was that a full-image path was required. I think it will be nice to add that info to the usage description to help silly folks like myself.

**Comment by zvin** [comment]
@taeold thanks for reporting that.
The latest resin-preload version (1.4.0) released today allows to use relative paths for the disk image and the splash image: https://www.npmjs.com/package/resin-preload
